using Xunit;

namespace FirmwareKit.Compress.Tests;

/// <summary>
/// 真实文件测试：对 tools/generate-real-files.sh 生成的各格式真实压缩文件
/// 执行枚举（检测）、解压与重压缩，并与原始样本逐字节比对。
/// <para>Real-file tests: for the real compressed files generated by
/// tools/generate-real-files.sh, verify enumeration (detection), decompression and
/// re-compression byte-for-byte against the original sample.</para>
/// <para>RealFiles 目录缺失时测试被跳过（先运行 tools/generate-real-files.sh）。</para>
/// </summary>
public class RealFileTests
{
    private sealed record RealFileCase(string FileName, CompressionFormat Format, bool AutoDetectable);

    private static readonly RealFileCase[] Cases =
    {
        new("sample.bin.gz", CompressionFormat.Gzip, true),
        new("sample.bin.bz2", CompressionFormat.Bzip2, true),
        new("sample.bin.xz", CompressionFormat.Xz, true),
        new("sample.bin.lzma", CompressionFormat.Lzma, true),
        new("sample.bin.br", CompressionFormat.Brotli, false),   // brotli 无固定魔数
        new("sample.bin.zlib", CompressionFormat.Zlib, true),
        new("sample.bin.deflate", CompressionFormat.Deflate, false), // 原始 deflate 无头
        new("sample.bin.lz4", CompressionFormat.Lz4, true),
        new("sample.bin.lz4_legacy", CompressionFormat.Lz4Legacy, true),
        new("sample.bin.lz4_lg", CompressionFormat.Lz4Lg, true),
        new("sample.bin.zstd", CompressionFormat.Zstd, true),
        new("sample.bin.lzop", CompressionFormat.Lzop, true),
        new("sample.bin.zopfli", CompressionFormat.Zopfli, true), // 检测结果为 gzip
    };

    private static string RealFilesDir => Path.Combine(AppContext.BaseDirectory, "RealFiles");

    private static byte[]? LoadSample()
    {
        string samplePath = Path.Combine(RealFilesDir, "sample.bin");
        return File.Exists(samplePath) ? File.ReadAllBytes(samplePath) : null;
    }

    private static void EnsureRealFiles()
    {
        if (!Directory.Exists(RealFilesDir) || LoadSample() == null)
            Assert.Skip("RealFiles 缺失，请先运行 tools/generate-real-files.sh");
    }

    public static IEnumerable<object[]> GetCases() => Cases.Select(c => new object[] { c.FileName, c.Format, c.AutoDetectable });

    [Fact]
    public void EveryFormat_HasARealFile()
    {
        EnsureRealFiles();

        foreach (var format in CompressionFormats.All.Select(f => f.Format))
        {
            var match = Cases.FirstOrDefault(c => c.Format == format);
            Assert.NotNull(match);
            Assert.True(File.Exists(Path.Combine(RealFilesDir, match!.FileName)),
                $"缺少真实文件: {match.FileName} ({format})");
        }
    }

    [Fact]
    public void Manifest_Exists()
    {
        EnsureRealFiles();
        Assert.True(File.Exists(Path.Combine(RealFilesDir, "manifest.txt")));
    }

    [Theory]
    [MemberData(nameof(GetCases))]
    public void Detect_IdentifiesExpectedFormat(string fileName, CompressionFormat format, bool autoDetectable)
    {
        EnsureRealFiles();

        string path = Path.Combine(RealFilesDir, fileName);
        var detected = CompressionService.DetectFile(path);

        if (autoDetectable)
        {
            // Zopfli 输出为标准 gzip，检测为 Gzip。
            var expected = format == CompressionFormat.Zopfli ? CompressionFormat.Gzip : format;
            Assert.Equal(expected, detected);
        }
        else
        {
            Assert.Equal(CompressionFormat.None, detected);
        }
    }

    [Theory]
    [MemberData(nameof(GetCases))]
    public void Decompress_RealFile_MatchesSampleByteForByte(string fileName, CompressionFormat format, bool autoDetectable)
    {
        EnsureRealFiles();
        var sample = LoadSample()!;

        string path = Path.Combine(RealFilesDir, fileName);
        using var input = File.OpenRead(path);
        using var output = new MemoryStream();

        if (autoDetectable)
            CompressionService.Decompress(input, output, CompressionService.DetectFile(path));
        else
            CompressionService.Decompress(input, output, format);

        Assert.Equal(sample, output.ToArray());
    }

    [Theory]
    [MemberData(nameof(GetCases))]
    public void Recompress_RealFileFormat_RoundTripsSample(string fileName, CompressionFormat format, bool autoDetectable)
    {
        EnsureRealFiles();
        var sample = LoadSample()!;

        // Verify the real fixture exists and, when auto-detectable, that its magic is
        // recognized; this also makes both theory parameters meaningful.
        string path = Path.Combine(RealFilesDir, fileName);
        Assert.True(File.Exists(path), $"missing real file: {fileName}");
        if (autoDetectable)
        {
            var expected = format == CompressionFormat.Zopfli ? CompressionFormat.Gzip : format;
            Assert.Equal(expected, CompressionService.DetectFile(path));
        }

        // 用库对原始样本压缩，再解压，逐字节比对。
        var compressed = CompressionService.Compress(sample, format);
        var decompressed = CompressionService.Decompress(compressed, format);

        Assert.Equal(sample, decompressed);
    }
}
